sudo: false
language: ruby
cache:
  directories:
    - vendor/bundle
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head
addons:
  apt:
    packages:
      - google-chrome-stable
      - chromium-chromedriver
env:
  - "RAILS_VERSION=4.2.11.1 BUNDLER_VERSION=1.17.3"
  - "RAILS_VERSION=5.2.3 BUNDLER_VERSION=2.0.1"
  - "RAILS_VERSION=6.0.0.rc1 BUNDLER_VERSION=2.0.1"
matrix:
  allow_failures:
    - rvm: ruby-head
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
before_install:
  - rm Gemfile.lock
  - gem install bundler -v ${BUNDLER_VERSION}
install:
  - bundle _${BUNDLER_VERSION}_ install --path vendor/bundle
after_success: bundle exec codeclimate-test-reporter
